"""
Django settings for learning_platform project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#r%j=p*5tx%*32e&af2vg1&hhb0frc%h=80)1-apfeh-pudvof'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'cogito-7zrt.onrender.com', 'e-learning-theta-ten.vercel.app', 'e-learning-git-main-patryks-projects-e8ee70da.vercel.app', 'e-learning-r1fw6hxe1-patryks-projects-e8ee70da.vercel.app']

# Security settings for production
SECURE_SSL_REDIRECT = os.getenv('RAILWAY_ENVIRONMENT') or os.getenv('RENDER')  # Set to True in production
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Session settings
SESSION_COOKIE_SECURE = os.getenv('RAILWAY_ENVIRONMENT') or os.getenv('RENDER')
SESSION_COOKIE_HTTPONLY = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
    'learningplatform',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'learning_platform.middleware.FirebaseAuthenticationMiddleware',
]

ROOT_URLCONF = 'learning_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'learning_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "https://cogito-7zrt.onrender.com",
    "https://e-learning-theta-ten.vercel.app",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://localhost:3000",
    "https://e-learning-git-main-patryks-projects-e8ee70da.vercel.app",
    "https://e-learning-r1fw6hxe1-patryks-projects-e8ee70da.vercel.app"
]
CORS_ALLOW_ALL_ORIGINS = not (os.getenv('RAILWAY_ENVIRONMENT') or os.getenv('RENDER'))  # Wyłączone w produkcji
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "HEAD"]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-forwarded-proto',
    'x-forwarded-for',
]

CSRF_TRUSTED_ORIGINS = [
    "https://e-learning-theta-ten.vercel.app",  # <-- PODMIEN NA SWOJĄ DOMENĘ VERCEL
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]
CSRF_COOKIE_SECURE = os.getenv('RAILWAY_ENVIRONMENT') or os.getenv('RENDER')
CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False
SESSION_COOKIE_SAMESITE = None
CSRF_COOKIE_SAMESITE = None

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'learning_platform.authentication.FirebaseAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom user model
AUTH_USER_MODEL = 'api.User'

# Railway/Render configuration
if os.getenv('RAILWAY_ENVIRONMENT') or os.getenv('RENDER'):
    ALLOWED_HOSTS = ['*', 'cogito-7zrt.onrender.com', 'e-learning-theta-ten.vercel.app']
    DEBUG = False
    # Dodaj domenę Vercel do CSRF_TRUSTED_ORIGINS w produkcji
    CSRF_TRUSTED_ORIGINS = [
        f"https://{os.getenv('RAILWAY_PUBLIC_DOMAIN', 'localhost')}",
<<<<<<< HEAD
        f"https://{os.getenv('RENDER_EXTERNAL_HOSTNAME', 'localhost')}",
        "https://cogito-7zrt.onrender.com",
        "https://e-learning-theta-ten.vercel.app",
    ]
    # Dodaj domenę Vercel do CORS w produkcji
    CORS_ALLOWED_ORIGINS = [
        f"https://{os.getenv('RENDER_EXTERNAL_HOSTNAME', 'cogito-7zrt.onrender.com')}",
        "https://cogito-7zrt.onrender.com",
        "https://e-learning-theta-ten.vercel.app",
    ]
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'cogito-7zrt.onrender.com', 'e-learning-theta-ten.vercel.app']
=======
        "https://cogito-7zrt.onrender.com",  # <-- PODMIEN NA SWOJĄ DOMENĘ VERCEL
    ]
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'cogito-7zrt.onrender.com', 'https://e-learning-git-main-patryks-projects-e8ee70da.vercel.app/', 'https://e-learning-r1fw6hxe1-patryks-projects-e8ee70da.vercel.app/']
>>>>>>> add1fdc6ca3c4aad48d9a1d455cf0d6283b670f6
    DEBUG = True
    # Dodaj domenę Vercel do CORS w development
    CORS_ALLOWED_ORIGINS = [
        "https://cogito-7zrt.onrender.com",
        "https://e-learning-theta-ten.vercel.app",
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "https://localhost:3000",
    ]
