# Generated by Django 5.2.3 on 2025-06-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningplatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='pdfUrls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
