# Generated by Django 5.0.2 on 2025-07-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningplatform', '0002_course_links_course_pdfurls_course_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
