# Generated by Django 5.0.2 on 2025-07-19 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningplatform', '0005_alter_course_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_by'], name='learningpla_created_80cf9d_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='learningpla_is_acti_7bdbcb_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_at'], name='learningpla_created_0b37e7_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['subject'], name='learningpla_subject_3020c0_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['year_of_study'], name='learningpla_year_of_cf33d2_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='learningpla_slug_ce5f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='courseassignment',
            index=models.Index(fields=['course'], name='learningpla_course__0a50e1_idx'),
        ),
        migrations.AddIndex(
            model_name='courseassignment',
            index=models.Index(fields=['student'], name='learningpla_student_e1c4f0_idx'),
        ),
        migrations.AddIndex(
            model_name='courseassignment',
            index=models.Index(fields=['is_active'], name='learningpla_is_acti_912122_idx'),
        ),
        migrations.AddIndex(
            model_name='courseassignment',
            index=models.Index(fields=['assigned_date'], name='learningpla_assigne_001b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='usergroup',
            index=models.Index(fields=['created_by'], name='learningpla_created_6bab46_idx'),
        ),
        migrations.AddIndex(
            model_name='usergroup',
            index=models.Index(fields=['created_at'], name='learningpla_created_997106_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user_type'], name='learningpla_user_ty_9faa4d_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['year_of_study'], name='learningpla_year_of_a330d0_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['created_at'], name='learningpla_created_937b51_idx'),
        ),
    ]
