# Generated by Django 5.0.2 on 2025-08-01 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningplatform', '0008_alter_quiz_options_quiz_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['firebase_id'], name='learningpla_firebas_b4d035_idx'),
        ),
    ]
