# Generated by Django 5.0.2 on 2025-08-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningplatform', '0009_quiz_firebase_id_quiz_learningpla_firebas_b4d035_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of attempts allowed for this quiz'),
        ),
    ]
