# Generated by Django 5.0.2 on 2025-08-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='time_spent_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
