# Generated by Django 4.2.7 on 2025-08-01 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_progress_time_spent_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLearningTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_time', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Learning Time',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
