# Generated by Django 4.2.7 on 2025-08-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userlearningtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
