# Generated by Django 5.0.2 on 2025-08-09 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_course_firebase_id'),
        ('api', '0005_grade'),
    ]

    operations = [
    ]
